/* Extend the existing desktop pages; mobile keeps its four operational tabs. */
(function(root){
'use strict';
const A=root.TsukinowaAccounting,el=id=>document.getElementById(id),B=()=>root.TsukinowaBusinessUI,enabled=()=>B().isEnabled(),uid=()=>crypto.randomUUID(),esc=s=>bizEsc(String(s??''));
let data={},expenseEdit=null,importing=false;
const old={};for(const n of ['addExpense','deleteExpense','renderExpenses','renderBank','importBankCsv','autoSuggestBank','matchBankSale','matchBankExpense','renderMonthly','bizPaid','bizOutstanding','renderSales','renderDashboard','exportDecisionCsv','exportBackup'])old[n]=root[n];
function isAdmin(){if(!enabled()||B().getClient()?.getState().role!=='admin'){alert('管理者のクラウドアカウントでログインしてください。');return false;}return true;}
function rev(n,id){return B().getSync()?.getRevision(n,id)||0;}
function send(c){if(!isAdmin())return;return B().enqueue(c);}
const value=id=>el(id)?.value||'',table=(headers,body)=>`<div class="biz-table-wrap"><table class="biz-table"><thead><tr>${headers.map(h=>'<th>'+esc(h)+'</th>').join('')}</tr></thead><tbody>${body||'<tr><td colspan="20">記録はありません。</td></tr>'}</tbody></table></div>`,cell=x=>'<td>'+esc(x)+'</td>',money=x=>bizMoney(Number(x)||0);
function notice(message){el('accountingMessage').textContent=message;}
function guard(fn){return async(...args)=>{try{return await fn(...args);}catch(e){notice(e.message);alert(e.message);}};}
function flatten(rows){return rows.map(r=>({...r.payload,id:r.id,createdAt:r.createdAt,updatedAt:r.updatedAt,createdBy:r.createdBy,updatedBy:r.updatedBy,revision:r.revision}));}
function hydrate(rows){data={};for(const n of ['sales','payments',...A.COLLECTIONS])data[n]=flatten(rows[n]||[]);data.sales.push(...flatten(rows.receivables||[]));bizState.expenses=data.expenses.filter(A.live).map(e=>({...e,date:e.expenseDate,method:e.paymentMethod,memo:e.description}));bizState.bank=data.bankTransactions.map(b=>({...b,date:b.bankTransactionDate,desc:b.description,matched:b.status==='照合済'}));renderCash();renderReceivables();}
root.TsukinowaAccountingUI={hydrate,role:()=>{expenseEdit=null;},getData:()=>data};
root.bizPaid=function(s){if(!enabled())return old.bizPaid(s);return A.ledger([s],data.payments||[]).sales[0]?.paid||0;};
root.bizOutstanding=function(s){if(!enabled())return old.bizOutstanding(s);return Number(s.amount)-bizPaid(s);};
root.addExpense=guard(()=>{if(!enabled())return old.addExpense();const expense={expenseDate:value('expDate'),category:value('expCategory'),paymentMethod:value('expMethod'),vendor:value('expVendor'),description:value('expMemo'),amount:A.money(value('expAmount')),bankAccount:value('expBankAccount'),receiptAttachmentRef:value('expAttachment')};A.date(expense.expenseDate);const expenseId=expenseEdit?.id||'expense_'+uid();if(send({type:'saveExpense',expenseId,expense,expectedRevision:expenseEdit?.revision||0})){expenseEdit=null;['expAmount','expVendor','expMemo','expAttachment'].forEach(id=>el(id).value='');notice('支出を同期キューに保存しました。');}});
root.accountingEditExpense=function(id){if(!isAdmin())return;const e=data.expenses.find(x=>x.id===id);if(!e)return;expenseEdit={id,revision:rev('expenses',id)};for(const [input,key] of [['expDate','expenseDate'],['expCategory','category'],['expMethod','paymentMethod'],['expVendor','vendor'],['expMemo','description'],['expAmount','amount'],['expBankAccount','bankAccount'],['expAttachment','receiptAttachmentRef']])el(input).value=e[key]||'';el('expAmount').scrollIntoView({behavior:'smooth'});};
root.deleteExpense=function(id){if(!enabled())return old.deleteExpense(id);if(!isAdmin())return;const reason=prompt('支出の取消理由（記録は保持されます）');if(reason)send({type:'deleteExpense',expenseId:id,reason,expectedRevision:rev('expenses',id)});};
root.renderExpenses=function(){if(!enabled())return old.renderExpenses();const m=value('expenseMonth');el('expenseRows').innerHTML=(data.expenses||[]).filter(e=>A.live(e)&&(!m||e.expenseDate.startsWith(m))).map(e=>'<tr>'+[e.expenseDate,e.category,e.vendor,e.description,e.paymentMethod,money(e.amount)].map(cell).join('')+`<td><button class="biz-btn" onclick="accountingEditExpense('${esc(e.id)}')">訂正</button><button class="biz-btn danger" onclick="deleteExpense('${esc(e.id)}')">取消</button></td></tr>`).join('');renderCash();};
function renderCash(){if(!el('cashRows'))return;const m=value('expenseMonth'),rows=A.cashRows(data.cashLedger||[]);el('cashBalance').textContent=money(rows.at(-1)?.runningBalance||0);el('cashRows').innerHTML=table(['日付','区分','分類','摘要','金額','残高'],rows.filter(r=>!m||r.date.startsWith(m)).map(r=>'<tr>'+[r.date,r.type==='income'?'収入':'支出',r.category,r.description,money(r.amount),money(r.runningBalance)].map(cell).join('')+'</tr>').join(''));}
root.accountingCashAdjustment=guard(()=>{const cashTxnId='adjust_'+uid();if(send({type:'cashAdjustment',cashTxnId,date:value('cashAdjustDate'),direction:value('cashAdjustType'),amount:A.money(value('cashAdjustAmount')),description:value('cashAdjustReason')})){el('cashAdjustAmount').value='';el('cashAdjustReason').value='';}});
root.importBankCsv=guard(async()=>{if(!enabled())return old.importBankCsv();if(!isAdmin()||importing)return;const file=el('bankFile').files[0];if(!file)throw Error('CSVを選択してください。');importing=true;try{const bytes=await file.arrayBuffer();let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch(_){text=new TextDecoder('shift_jis',{fatal:true}).decode(bytes);}const records=await A.parseBank(text,value('bankAccountName'),B().getClient().digest);let count=0;for(const bank of records){if(!send({type:'importBank',bank}))throw Error('端末に同期キューを保存できませんでした。元CSVを保持して再試行してください。');count++;}el('bankImportStatus').textContent=count+'件を確認しました。重複を除いて同期します。';}finally{importing=false;}});
root.autoSuggestBank=function(){if(!enabled())return old.autoSuggestBank();};
root.matchBankSale=(bankTxnId,targetId)=>enabled()?root.accountingConfirmBank(bankTxnId,{targetType:'sale',targetId,paymentId:''}):old.matchBankSale(bankTxnId,targetId);
root.matchBankExpense=(bankTxnId,targetId)=>enabled()?root.accountingConfirmBank(bankTxnId,{targetType:'expense',targetId,paymentId:''}):old.matchBankExpense(bankTxnId,targetId);
root.accountingConfirmBank=(bankTxnId,target)=>{if(!isAdmin())return;const b=data.bankTransactions.find(b=>b.id===bankTxnId);if(!b)return;if(!target){try{target=JSON.parse(value('bankTarget_'+bankTxnId));}catch(_){return alert('照合先を選択してください。');}}if(confirm(`${b.bankTransactionDate} ${b.bankAccount} ${money(b.amount)}\nこの銀行明細と選択した記録を照合しますか？`))send({type:'bankMatch',bankTxnId,...target,expectedRevision:rev('bankTransactions',bankTxnId)});};
root.accountingUnmatchBank=bankTxnId=>{if(!isAdmin())return;const reason=prompt('照合解除の理由（変更履歴は保持されます）');if(reason)send({type:'bankUnmatch',bankTxnId,reason,expectedRevision:rev('bankTransactions',bankTxnId)});};
root.accountingExcludeBank=(bankTxnId,excluded)=>{if(!isAdmin())return;const reason=prompt(excluded?'除外理由':'除外解除の理由');if(reason)send({type:'bankExclude',bankTxnId,excluded,reason,expectedRevision:rev('bankTransactions',bankTxnId)});};
function targets(b){const out=[];if(b.incoming){for(const s of (data.sales||[]).filter(A.live))out.push({targetType:'sale',targetId:s.id,paymentId:'',label:`請求 ${s.customer} / ${s.invoiceNo||s.id} / 未収 ${money(bizOutstanding(s))}`});for(const p of (data.payments||[]).filter(p=>A.live(p)&&p.confirmation==='pending-bank'&&p.amount===b.amount)){const s=data.sales.find(s=>s.id===p.saleId);if(s&&A.live(s))out.push({targetType:'sale',targetId:s.id,paymentId:p.id,label:`仮入金 ${s.customer} ${money(p.amount)} ${p.paymentDate}`});}}
 else{for(const e of (data.expenses||[]).filter(e=>A.live(e)&&!e.bankTxnId&&e.paymentMethod!=='現金'&&e.paymentMethod!=='月締'&&e.amount===b.amount))out.push({targetType:'expense',targetId:e.id,paymentId:'',label:`支出 ${e.vendor} ${e.expenseDate} ${money(e.amount)}`});for(const t of (data.supplierTransactions||[]).filter(t=>A.live(t)&&!t.bankTxnId&&t.paymentMethod!=='現金'&&['payment','prepayment'].includes(t.type)&&t.amount===b.amount))out.push({targetType:'supplier',targetId:t.id,paymentId:'',label:`仕入先支払 ${data.suppliers.find(s=>s.id===t.supplierId)?.supplierName} ${t.date} ${money(t.amount)}`});}return out;}
root.renderBank=function(){if(!enabled())return old.renderBank();const rows=(data.bankTransactions||[]).filter(A.live).slice().sort((a,b)=>b.bankTransactionDate.localeCompare(a.bankTransactionDate));el('bankRows').innerHTML=rows.map(b=>{const suggestions=A.suggestions(b,data),state=b.status==='未照合'&&suggestions.length?'候補あり':b.status;let controls='';if(b.status==='照合済')controls=`${esc(b.matchType)} ${esc(b.matchId)} <button class="biz-btn" onclick="accountingUnmatchBank('${esc(b.id)}')">解除</button>`;else if(b.status==='除外')controls=`${esc(b.excludeReason)} <button class="biz-btn" onclick="accountingExcludeBank('${esc(b.id)}',false)">除外解除</button>`;else{controls=`<select id="bankTarget_${esc(b.id)}"><option value="">照合先を選択（自動確定しません）</option>`+targets(b).map(t=>{const sug=suggestions.find(s=>s.kind===t.targetType&&s.id===t.targetId&&s.paymentId===t.paymentId);const {label,...v}=t;return `<option value="${esc(JSON.stringify(v))}">${esc((sug?`候補 ${sug.score}点 (${sug.reasons.join('・')}) / `:'')+label)}</option>`;}).join('')+`</select><button class="biz-btn ok" onclick="accountingConfirmBank('${esc(b.id)}')">照合確定</button><button class="biz-btn" onclick="accountingExcludeBank('${esc(b.id)}',true)">除外</button>`;}return '<tr>'+[b.bankTransactionDate,b.description+' / '+b.bankAccount,b.incoming?money(b.incoming):'',b.outgoing?money(b.outgoing):''].map(cell).join('')+'<td>'+controls+'</td>'+cell(state)+'</tr>';}).join('');};
function renderReceivables(){if(!el('receivableRows'))return;const rs=currentReceivables();el('receivableRows').innerHTML=table(['売上日','請求日','顧客','請求額','入金済','未収','最終入金日','経過日数','状態'],rs.map(s=>'<tr>'+[s.salesDate,s.invoiceDate,s.customer,money(s.amount),money(s.paid),money(s.outstanding),s.lastPaymentDate,s.ageDays,s.status].map(cell).join('')+'</tr>').join(''));}
root.renderDashboard=function(){old.renderDashboard();if(enabled()){const rs=A.receivables(data.sales||[],data.payments||[],todayISO());el('kpiPayments').textContent=money(A.monthly(data,bizNowMonth()).income);el('kpiReceivable').textContent=money(rs.reduce((n,r)=>n+r.outstanding,0));el('attentionList').textContent='未入金 '+rs.filter(r=>r.outstanding>0).length+'件 ／ 銀行未照合 '+(data.bankTransactions||[]).filter(b=>!['照合済','除外'].includes(b.status)).length+'件 ／ カレンダー取込 '+bizState.calendar.length+'件';}};
function currentSales(){return A.salesRows(data.sales||[],data.payments||[],value('salesMonth'));}
function currentReceivables(){return A.receivables(data.sales||[],data.payments||[],value('receivableAsOf')||todayISO());}
root.renderSales=function(){if(!enabled())return old.renderSales();el('salesRows').innerHTML=currentSales().map(s=>'<tr>'+[s.salesDate,s.customer,s.content,money(s.amount),s.invoiceDate||'—',money(s.paid),money(s.outstanding)].map(cell).join('')+cell(s.status)+`<td>${s.outstanding>0?`<button class="biz-btn" onclick="selectSaleForPayment('${esc(s.id)}')">入金</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="9">対象月の売上はありません。</td></tr>';renderPaymentSaleOptions();renderReceivables();};
root.renderMonthly=function(){old.renderMonthly();if(!enabled()||!el('monthlyDetails'))return;const m=A.monthly(data,value('monthlyMonth')||bizNowMonth());for(const [id,key] of [['mSales','sales'],['mPayments','income'],['mExpenses','expenseTotal'],['mCashDiff','cashFlowDifference']])el(id).textContent=money(m[key]);el('monthlyDetails').innerHTML=table(['集計','金額'],[['銀行入金',m.bankIncome],['現金入金',m.cashIncome],...m.incomeChannels.map(c=>['入金経路 / '+c.channel+(c.platformName?' / '+c.platformName:''),c.amount]),['月末未収残高',m.receivables],['現金収入',m.cashReceipts],['現金支出',m.cashExpenses],['月末現金残高',m.cashBalance],['仕入先前払',m.supplierPrepayment],['仕入先月次請求',m.supplierInvoice],['仕入先支払',m.supplierPayment],...Object.entries(m.categories).map(([k,v])=>['支出 / '+k,v]),...m.suppliers.map(s=>['仕入先残高 / '+s.supplierName,s.currentBalance])].map(r=>'<tr>'+cell(r[0])+cell(money(r[1]))+'</tr>').join(''));el('supplierReconciliationStatus').textContent=m.suppliers.length?'既存の仕入先履歴は月次集計・銀行照合・年度CSVに保持しています。PDF請求書との照合は準備中です。':'PDF請求書と銀行支払の照合は準備中です。新たな台帳入力は不要です。';};
function exportRows(kind){const month=value('monthlyMonth')||bizNowMonth(),m=A.monthly(data,month);switch(kind){case'monthly':return [['対象月','区分','金額'],...Object.entries({売上:m.sales,銀行入金:m.bankIncome,現金入金:m.cashIncome,入金合計:m.income,支出:m.expenseTotal,収支差額:m.cashFlowDifference,月末未収:m.receivables,月末現金残高:m.cashBalance,現金収入:m.cashReceipts,現金支出:m.cashExpenses,仕入先前払:m.supplierPrepayment,仕入先月次請求:m.supplierInvoice,...m.categories}).map(([k,v])=>[month,k,v]),...m.suppliers.map(s=>[month,'仕入先残高 / '+s.supplierName,s.currentBalance]),...m.incomeChannels.map(c=>[month,'入金経路 / '+c.channel+(c.platformName?' / '+c.platformName:''),c.amount])];
case'expenses':return [['expenseId','支出日','分類','仕入先','摘要','金額','支払方法','銀行口座','添付参照','取消日'],...(data.expenses||[]).map(e=>[e.id,e.expenseDate,e.category,e.vendor,e.description,e.amount,e.paymentMethod,e.bankAccount,e.receiptAttachmentRef,e.deletedAt])];
case'payments':return [['入金ID','売上ID','入金日','金額','入金経路','プラットフォーム名','確認状態'],...(data.payments||[]).filter(p=>String(p.paymentDate||p.date).slice(0,7)===month).map(p=>[p.id,p.saleId,p.paymentDate||p.date,p.amount,A.paymentChannel(p).channel,A.paymentChannel(p).platformName,p.confirmation])];
case'sales':return [['売上ID','売上日','顧客','内容','請求額','請求日','入金済','未収','状態','最終入金日','入金経路','プラットフォーム名'],...currentSales().map(s=>[s.id,s.salesDate,s.customer,s.content,s.amount,s.invoiceDate,s.paid,s.outstanding,s.status,s.lastPaymentDate,...['channel','platformName'].map(k=>[...new Set(A.paymentChannels(A.ledger([s],data.payments||[]).payments).map(c=>c[k]).filter(Boolean))].join(' / '))])];
case'receivables':return [['売上ID','売上日','請求日','顧客','請求額','入金済','未収','最終入金日','経過日数','状態'],...currentReceivables().map(s=>[s.id,s.salesDate,s.invoiceDate,s.customer,s.amount,s.paid,s.outstanding,s.lastPaymentDate,s.ageDays,s.status])];
case'suppliers':return [['仕入先ID','仕入先','取引ID','日付','区分','金額','請求月','摘要','取消日','期首残高','現在残高'],...(data.suppliers||[]).map(s=>[s.id,s.supplierName,'',s.openingDate,'期首',s.openingBalance,'','','',s.openingBalance,A.supplierBalance(s,data.supplierTransactions||[])]),...(data.supplierTransactions||[]).map(t=>[t.supplierId,data.suppliers.find(s=>s.id===t.supplierId)?.supplierName,t.id,t.date,t.type,t.amount,t.invoiceMonth,t.description,t.deletedAt,'',''])];
case'bank':return [['bankTxnId','銀行取引日','銀行口座','摘要','入金','出金','状態','照合区分','照合先','入金ID'],...(data.bankTransactions||[]).map(b=>[b.id,b.bankTransactionDate,b.bankAccount,b.description,b.incoming,b.outgoing,b.status==='未照合'&&A.suggestions(b,data).length?'候補あり':b.status,b.matchType,b.matchId,b.paymentId])];
case'cash':return [['cashTxnId','日付','区分','分類','摘要','金額','残高','入金ID','支出ID'],...A.cashRows(data.cashLedger||[]).map(c=>[c.cashTxnId,c.date,c.type,c.category,c.description,c.amount,c.runningBalance,c.linkedPaymentId,c.linkedExpenseId])];default:throw Error('出力形式が不正です。');}}
root.accountingExport=kind=>{if(!isAdmin())return;const text=A.csv(exportRows(kind)),url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=kind+'_'+todayISO()+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
root.exportBackup=function(){if(!enabled())return old.exportBackup();if(!isAdmin())return;const sync=B().getSync(),blob=new Blob([JSON.stringify({schemaVersion:3,exportedAt:new Date().toISOString(),records:sync.getRows(),pending:sync.getQueue()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='tsukinowa-accounting-backup_'+todayISO()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
root.exportDecisionCsv=function(){if(!enabled())return old.exportDecisionCsv();root.accountingExport('monthly');};
root.TsukinowaAccountingUI.exportRows=exportRows;
root.accountingMigrate=guard(async()=>{if(!isAdmin())return;const client=B().getClient(),who=client.getState(),localKey=`tsukinowa_cloud_local_${who.projectId}_${who.companyId}_${who.user.uid}`,raw=localStorage.getItem(localKey),legacy=TsukinowaCloudCore.backupLegacy(localStorage);if(legacy.errors.length)throw Error('旧データに読込エラーがあります。原本を保持して中止しました。');const phase2=JSON.parse(raw||'{}'),source=TsukinowaCloudCore.canonical({legacy:legacy.raw,phase2,account:value('bankAccountName')}),service=B().getSync().service,sourceId=await service.stable('accounting_migration',source),backupKey='tsukinowa_cloud_backup_'+sourceId;
 if(!localStorage.getItem(backupKey))localStorage.setItem(backupKey,JSON.stringify({legacy,phase2Raw:raw,createdAt:new Date().toISOString()}));if(!localStorage.getItem(backupKey))throw Error('バックアップを保存できません。');
 const button=el('accountingMigrateButton');button.disabled=true;try{const marker=await service.execute({type:'migrationStatus',operationId:uid(),sourceId});if(marker?.migrationVersion===3&&marker.completed){notice('会計データは移行済みです（重複なし）。');return;}
 const expenseMap=new Map(),bankMap=new Map();for(const e of [...legacy.business.expenses||[],...phase2.expenses||[]]){if(!e.id)throw Error('IDのない旧支出があります。');expenseMap.set(e.id,e);}for(const b of [...legacy.business.bank||[],...phase2.bank||[]]){if(!b.id)throw Error('IDのない旧銀行記録があります。');bankMap.set(b.id,b);}
 const commands=[];for(const e of expenseMap.values()){const id=await service.stable('expense','legacy:'+e.id);commands.push({type:'migrateAccounting',collection:'expenses',id,payload:{expenseId:id,expenseDate:A.date(e.expenseDate||e.date),category:A.CATEGORIES.includes(e.category)?e.category:'その他',vendor:e.vendor||'',description:e.description||e.memo||'',amount:A.money(e.amount),paymentMethod:e.paymentMethod||e.method||'銀行振込',bankAccount:e.bankAccount||(e.method==='現金'?'cash':''),receiptAttachmentRef:e.receiptAttachmentRef||'',legacy:e,deletedAt:null}});}
 if(bankMap.size){const oldRows=[...bankMap.values()],csv=A.csv([['日付','摘要','入金','出金'],...oldRows.map(b=>[b.date,b.desc,b.incoming||0,b.outgoing||0])]),records=await A.parseBank(csv,value('bankAccountName'),client.digest);for(let i=0;i<records.length;i++){const b=records[i],old=oldRows[i];commands.push({type:'migrateAccounting',collection:'bankTransactions',id:b.bankTxnId,payload:{...b,status:old.matched?'除外':'未照合',excludeReason:old.matched?'旧システムで照合済み。二重記帳防止のため要確認。':'',legacy:old,reviewRequired:!!old.matched}});}}
 // All input is validated before the first cloud write. Existing records are never replaced.
 let count=0;for(const c of commands){await service.execute({...c,operationId:await service.stable('mig3',sourceId+c.collection+c.id+who.user.uid)});notice(`会計移行中 ${++count}/${commands.length}（原本保持）`);}
 for(const n of ['payments','expenses','supplierTransactions'])for(const r of B().getSync().getRows()[n]||[])await service.execute({type:'backfillCash',collection:n,id:r.id,operationId:uid()});
 await service.execute({type:'accountingMigrationComplete',sourceId,backupKey,count,operationId:uid()});notice('会計移行成功。原本とバックアップを保持しています。旧照合済み銀行記録は除外欄で確認できます。');
 }catch(e){notice('会計移行失敗：'+e.message+'（原本・バックアップ保持、再実行可）');throw e;}finally{button.disabled=false;}});
function section(title,html){const d=document.createElement('div');d.className='biz-section';d.innerHTML='<div class="biz-section-head"><h2>'+title+'</h2></div>'+html;return d;}
const field=(label,id,type='text',extra='')=>`<div class="biz-field"><label for="${id}">${label}</label><input id="${id}" type="${type}" ${extra}></div>`;
const select=(label,id,values)=>`<div class="biz-field"><label for="${id}">${label}</label><select id="${id}">${values.map(v=>`<option value="${esc(v[0])}">${esc(v[1])}</option>`).join('')}</select></div>`;
document.addEventListener('DOMContentLoaded',()=>{
 const message=document.createElement('p');message.id='accountingMessage';message.setAttribute('role','status');el('cloudDialog').append(message);
 const migrate=document.createElement('button');migrate.id='accountingMigrateButton';migrate.className='biz-btn';migrate.textContent='旧支出・銀行記録を安全に移行 / 現金帳再構築';migrate.onclick=root.accountingMigrate;el('cloudMigration').append(migrate);
 el('expCategory').replaceChildren(...A.CATEGORIES.map(c=>new Option(c,c)));
 el('expMemo').parentElement.after(section('支出補足',`<div class="biz-form-grid">${field('銀行口座（現金なら不要）','expBankAccount')}${field('領収書添付参照（任意）','expAttachment')}</div><button class="biz-btn" onclick="accountingExport('expenses')">支出CSV</button>`));
 el('pageExpenses').append(section('現金帳（確認済み実収支）','<p>現在残高 <b id="cashBalance">¥0</b>。日付順に自動再計算します。</p><button class="biz-btn" onclick="accountingExport(\'cash\')">現金帳CSV</button><div id="cashRows"></div>'));
 el('pageExpenses').append(section('現金残高の調整',`<div class="biz-form-grid">${field('日付','cashAdjustDate','date')}${select('区分','cashAdjustType',[['income','増額'],['expense','減額']])}${field('金額','cashAdjustAmount','number')}${field('理由','cashAdjustReason')}</div><button class="biz-btn" onclick="accountingCashAdjustment()">調整を記録</button>`));
 el('bankFile').parentElement.before(section('銀行口座',field('同じ口座は同じ名前で取り込みます','bankAccountName','text','value="メイン口座"')+'<p class="biz-muted">UTF-8 / Shift_JIS。日付・摘要・入金・出金の列が必要です。候補は金額・日付・名称で判定し、管理者の確認後に照合します。</p><p id="bankImportStatus" role="status"></p><button class="biz-btn" onclick="accountingExport(\'bank\')">銀行照合結果CSV</button>'));
 el('pageSales').append(section('未収一覧',field('基準日','receivableAsOf','date')+'<button class="biz-btn" onclick="renderSales()">基準日で表示</button><button class="biz-btn" onclick="accountingExport(\'receivables\')">未収金CSV</button><button class="biz-btn" onclick="accountingExport(\'sales\')">売上・入金CSV</button><div id="receivableRows"></div>'));
 el('auditRows').parentElement.before(section('月次内訳','<p class="biz-muted">売上日・入金日・支出日を区別します。収支差額＝確認済み入金−支出。会計上の利益を表す数値ではありません。月末未収は売上日が月末以前の請求と月末までの確認済入金から計算します。</p><div id="monthlyDetails"></div>'));
 el('pageMonthly').append(section('仕入先照合（準備中）','<p id="supplierReconciliationStatus">PDF請求書と銀行支払の照合は準備中です。既存履歴は保持しています。</p><button class="biz-btn" onclick="accountingExport(\'suppliers\')">既存仕入先履歴CSV</button>'));
 el('monthlyDetails').before(section('入金経路','<button class="biz-btn" onclick="accountingExport(\'payments\')">対象月の入金一覧CSV</button>'));
 for(const id of ['cashAdjustDate','receivableAsOf'])el(id).value=todayISO();
});
})(window);
