(function(root){
'use strict';
const Y=root.TsukinowaYearEnd,B=()=>root.TsukinowaBusinessUI,el=id=>document.getElementById(id),esc=v=>bizEsc(String(v??''));
function state(){const who=B().getClient()?.getState();Y.assertAdmin(who);if(!B().isEnabled()||!B().getSync())throw Error('クラウドにログインしてください。');return who;}
function records(){return B().getSync().getRows();}
function data(){return Y.flatten(records());}
const year=()=>Number(el('yearEndYear').value),table=(headers,rows)=>'<div class="biz-table-wrap"><table class="biz-table"><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
function guard(fn){return async(...args)=>{try{state();return await fn(...args);}catch(e){alert(e.message);}};}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
root.yearEndExport=guard(name=>{const files=Y.exports(data(),year(),state(),el('auditUser').value,el('auditEntity').value);download(name,files[name],'text/csv;charset=utf-8');});
root.exportBackup=guard(()=>{const sync=B().getSync();if(sync.getQueue().length)throw Error('未同期データがあります。同期完了後にバックアップしてください。');if(!sync.isReady())throw Error('全データのクラウド同期完了を待ってください。');download('tsukinowa-backup_'+todayISO()+'.json',JSON.stringify(Y.backup(records(),state()),null,2),'application/json');});
root.importBackup=guard(async()=>{const file=el('backupFile').files[0];if(!file)throw Error('バックアップJSONを選択してください。');if(file.size>50*1024*1024)throw Error('50MB 以下のファイルを選択してください。');const preview=Y.validateBackup(JSON.parse(await file.text()),state());el('backupPreview').textContent=JSON.stringify(preview,null,2);});
root.yearEndTab=tab=>{try{state();}catch(_){return;}document.querySelectorAll('[data-year-panel]').forEach(p=>p.hidden=p.dataset.yearPanel!==tab);document.querySelectorAll('[data-year-tab]').forEach(b=>b.classList.toggle('active',b.dataset.yearTab===tab));root.renderYearEnd();};
root.renderYearEnd=function(){if(!el('yearEndYear'))return;const allowed=B().isEnabled()&&B().getClient()?.getState().role==='admin'&&!!B().getSync();el('yearEndTools').hidden=!allowed;if(el('cloudExport')){el('cloudExport').hidden=!allowed;el('cloudExport').onclick=root.exportBackup;}if(!allowed){for(const id of ['annualRows','yearChecks','yearAudit','backupPreview'])el(id).replaceChildren();return;}const d=data(),a=Y.annual(d,year());el('yearPeriod').textContent=a.start.replaceAll('-','/')+' ～ '+a.end.replaceAll('-','/');el('annualRows').innerHTML=table(['集計','金額'],Object.entries({年間売上:a.sales,銀行入金:a.bankIncome,現金入金:a.cashIncome,入金合計:a.income,期末未収金:a.receivables,年間支出:a.expenseTotal,現金支出:a.cashExpenses,銀行支出:a.bankExpenses,収支差額:a.cashFlowDifference,...a.categories}).map(([k,v])=>[k,bizMoney(v)]))+table(['月','売上','支出'],a.months.map(m=>[m.month,bizMoney(m.sales),bizMoney(m.expenseTotal)]));const checks=Y.checks(d,year());el('yearChecks').innerHTML=checks.length?table(['確認事項','ID','詳細'],checks.map(c=>[c.type,c.id,c.detail])):'確認事項はありません。';el('yearAudit').innerHTML=table(['誰','時間','entity','action','before','after','reason'],Y.audit(d,year(),el('auditUser').value,el('auditEntity').value).map(r=>[r.userId,r.timestamp?.seconds?new Date(r.timestamp.seconds*1000).toISOString():r.timestamp,r.entityType+' / '+r.entityId,r.action,JSON.stringify(r.before),JSON.stringify(r.after),r.reason||r.after?.reason||r.after?.deleteReason||'']));};
const previous=root.renderMonthly;root.renderMonthly=function(){previous();root.renderYearEnd();};
const oldRole=root.TsukinowaAccountingUI.role;root.TsukinowaAccountingUI.role=function(r){oldRole(r);root.renderYearEnd();};
document.addEventListener('DOMContentLoaded',()=>{const page=el('pageMonthly'),tools=document.createElement('div');tools.id='yearEndTools';tools.hidden=true;tools.innerHTML='<p><b>税理士確認用資料</b>。税額・申告内容は税理士が確認します。収支差額は確認済入金−支出です。銀行支出は銀行等で支払った支出（現金・月締を除く）です。</p><div class="biz-form-grid"><label>年度開始年（10月）<input id="yearEndYear" type="number" min="2000" max="9998" onchange="renderYearEnd()"></label><b id="yearPeriod"></b></div><div>'+['月次','年度','確認事項','エクスポート'].map((label,i)=>'<button class="biz-btn" data-year-tab="'+i+'" onclick="yearEndTab(\''+i+'\')">'+label+'</button>').join('')+'</div><div data-year-panel="1" hidden><div id="annualRows"></div></div><div data-year-panel="2" hidden><p>確認事項は提示のみです。データは自動変更しません。日付のない記録・ID重複は全期間を確認します。</p><div id="yearChecks"></div></div><div data-year-panel="3" hidden><div id="yearExports"></div><h2>バックアップ検証・プレビュー</h2><p>JSON は個人・取引情報を含みます。安全に保管してください。復元・上書きは実行しません。</p><pre id="backupPreview" style="white-space:pre-wrap"></pre><h2>監査</h2><label>ユーザーID <input id="auditUser" onchange="renderYearEnd()"></label><label>entityType <select id="auditEntity" onchange="renderYearEnd()"><option value="">全て</option>'+Y.COLLECTIONS.map(n=>'<option>'+n+'</option>').join('')+'</select></label><button class="biz-btn" onclick="yearEndExport(\'監査履歴.csv\')">監査CSV</button><div id="yearAudit"></div></div>';
const monthly=document.createElement('div');monthly.dataset.yearPanel='0';while(page.children.length>1)monthly.append(page.children[1]);page.append(tools);tools.append(monthly);el('yearEndYear').value=new Date().getFullYear()-(new Date().getMonth()<9?1:0);
const names=Object.keys(Y.exports(Y.flatten({}),year(),{role:'admin',companyId:'tsukinowa'})).filter(n=>n!=='監査履歴.csv');el('yearExports').innerHTML=names.map(n=>'<button class="biz-btn" onclick="yearEndExport(\''+n+'\')">'+n+'</button>').join('');const source=el('backupFile').closest('.biz-form-grid'),backupSection=document.createElement('div');backupSection.className='biz-section';for(const child of [...source.children].slice(2))backupSection.append(child);el('yearExports').after(backupSection);for(const label of backupSection.querySelectorAll('label'))if(label.textContent==='バックアップ復元')label.textContent='バックアップ検証';for(const button of backupSection.querySelectorAll('button'))if(button.getAttribute('onclick')==='importBackup()')button.textContent='検証・プレビュー';root.renderYearEnd();});
})(window);
