(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./accounting.js'):root.TsukinowaAccounting);if(typeof module==='object'&&module.exports)module.exports=api;else root.TsukinowaYearEnd=api;})(globalThis,function(A){
'use strict';
const COLLECTIONS=['calendarLinks','estimates','projects','documents','sales','receivables','payments',...A.COLLECTIONS,'auditLogs','settings','migrations'];
const assertAdmin=who=>{if(who?.role!=='admin'||who.companyId!=='tsukinowa')throw Error('管理者のみ利用できます。');};
const flatten=rows=>Object.fromEntries(COLLECTIONS.map(n=>[n,(rows[n]||[]).map(r=>r.payload?{...r.payload,id:r.id}:r)]));
const sum=rs=>rs.reduce((n,r)=>n+(Number(r.amount)||0),0),id=r=>r.id||r.documentId;
function period(startYear){const y=Number(startYear);if(!Number.isInteger(y)||y<2000||y>9998)throw Error('年度が不正です。');return {start:`${y}-10-01`,end:`${y+1}-09-30`,months:Array.from({length:12},(_,i)=>`${y+Math.floor((i+9)/12)}-${String((i+9)%12+1).padStart(2,'0')}`)};}
function effective(data){const docs=new Map((data.documents||[]).map(d=>[id(d),d])),seen=new Set();return {...data,payments:A.accountablePayments(data),sales:[...(data.sales||[]),...(data.receivables||[])].filter(s=>{const key=s.id||s.saleId||s.documentId;if(seen.has(key)||!A.live(s))return false;const d=docs.get(s.documentId);if(d&&!A.live(d))return false;seen.add(key);return true;})};}
function annual(data,year){const p=period(year),d=effective(data),months=p.months.map(m=>A.monthly(d,m)),within=(r,k)=>r[k]>=p.start&&r[k]<=p.end,expenses=(d.expenses||[]).filter(r=>A.live(r)&&within(r,'expenseDate')),total=k=>months.reduce((n,m)=>n+m[k],0),categories=Object.fromEntries(A.CATEGORIES.map(c=>[c,months.reduce((n,m)=>n+(m.categories[c]||0),0)]));return {...p,months,categories,sales:total('sales'),bankIncome:total('bankIncome'),cashIncome:total('cashIncome'),income:total('income'),receivables:A.receivables(d.sales,d.payments||[],p.end).reduce((n,s)=>n+s.outstanding,0),expenseTotal:total('expenseTotal'),cashExpenses:sum(expenses.filter(e=>e.paymentMethod==='現金')),bankExpenses:sum(expenses.filter(e=>e.paymentMethod!=='現金'&&e.paymentMethod!=='月締')),cashFlowDifference:total('cashFlowDifference')};}
const timestamp=r=>r.timestamp?.seconds?new Date(r.timestamp.seconds*1000).toISOString():r.timestamp||r.at||'';
const auditDate=r=>{const t=timestamp(r);return t&&Number.isFinite(Date.parse(t))?new Date(t).toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}):'';};
function audit(data,year,user='',entity=''){const p=period(year);return (data.auditLogs||[]).filter(r=>auditDate(r)>=p.start&&auditDate(r)<=p.end&&(!user||r.userId===user)&&(!entity||r.entityType===entity)).sort((a,b)=>timestamp(a).localeCompare(timestamp(b)));}
function checks(data,year){const p=period(year),d=effective(data),out=[],add=(type,r,detail)=>out.push({type,id:id(r)||r.paymentId||r.cashTxnId||r.bankTxnId||'',detail}),within=(r,k)=>r[k]>=p.start&&r[k]<=p.end;
for(const b of data.bankTransactions||[])if(A.live(b)&&within(b,'bankTransactionDate')&&!['照合済','除外'].includes(b.status))add('未照合銀行入出金',b,b.description);
for(const s of A.receivables(d.sales,d.payments||[],p.end))if(s.outstanding!==0)add('未収金',s,String(s.outstanding));
for(const [name,key] of [['sales','salesDate'],['payments','paymentDate'],['expenses','expenseDate'],['cashLedger','date']])for(const r of data[name]||[])if(A.live(r)&&within(r,key)&&(!Number.isSafeInteger(Number(r.amount))||Number(r.amount)<=0))add('金額0・異常金額',r,name);
for(const e of data.expenses||[])if(A.live(e)&&within(e,'expenseDate')&&!e.category)add('分類未設定',e,'支出 category');
for(const r of data.payments||[])if(A.confirmed(r)&&!r.paymentDate)add('入金日未設定',r,'paymentDate');
const seen=new Set(),invoice=new Map();for(const doc of data.documents||[]){const did=doc.documentId||doc.id;if(seen.has(did))add('同一 documentId 重複',doc,did);seen.add(did);if(['void','duplicate','cancelled'].includes(doc.status)&&((data.sales||[]).some(s=>A.live(s)&&s.documentId===did)||(data.payments||[]).some(r=>A.live(r)&&(r.documentId===did||r.id===doc.paymentId))))add('無効・重複帳票の関連記録',doc,doc.status);if(A.live(doc)&&['invoice','onoda'].includes(doc.docType)){const sale=doc.saleId||'sale_'+did;if(invoice.has(sale))add('同一売上に複数有効請求書',doc,sale);invoice.set(sale,did);}}
for(const c of A.cashRows(data.cashLedger||[]))if(within(c,'date')&&(!Number.isSafeInteger(c.runningBalance)||c.runningBalance<0))add('現金残高異常',c,String(c.runningBalance));return out;}
function exports(data,year,who,user='',entity=''){assertAdmin(who);const a=annual(data,year),d=effective(data),inYear=(rs,k)=>rs.filter(r=>r[k]>=a.start&&r[k]<=a.end),rows=(header,rs,keys)=>[header,...rs.map(r=>keys.map(k=>typeof k==='function'?k(r):r[k]))],json=v=>JSON.stringify(v??null),metrics={年間売上:a.sales,銀行入金:a.bankIncome,現金入金:a.cashIncome,入金合計:a.income,期末未収金:a.receivables,年間支出:a.expenseTotal,現金支出:a.cashExpenses,銀行支出:a.bankExpenses,収支差額:a.cashFlowDifference,...a.categories};
const files={
'年間売上一覧.csv':rows(['売上ID','帳票ID','売上日','顧客','金額'],inYear(d.sales.filter(s=>!s.receivableOnly),'salesDate'),['id','documentId','salesDate','customer','amount']),
'入金一覧.csv':rows(['入金ID','売上ID','入金日','金額','確認状態','計上対象','取消日'],inYear(data.payments||[],'paymentDate'),['id','saleId','paymentDate','amount','confirmation',r=>A.confirmed(r)&&d.payments.some(p=>p.id===r.id)?'yes':'no','deletedAt']),
'未収金一覧.csv':rows(['売上ID','顧客','売上日','売上','確認済入金','期末未収'],A.receivables(d.sales,d.payments||[],a.end).filter(s=>s.outstanding!==0),['id','customer','salesDate','amount','paid','outstanding']),
'支出一覧.csv':rows(['支出ID','日付','分類','仕入先','摘要','金額','支払方法','計上対象','取消日'],inYear(data.expenses||[],'expenseDate'),['id','expenseDate','category','vendor','description','amount','paymentMethod',r=>A.live(r)?'yes':'no','deletedAt']),
'現金出納帳.csv':rows(['ID','日付','摘要','収入','支出','残高','category','related entity'],inYear(A.cashRows(data.cashLedger||[]),'date'),['cashTxnId','date','description',r=>r.type==='income'?r.amount:0,r=>r.type==='expense'?r.amount:0,'runningBalance','category',r=>r.linkedPaymentId||r.linkedExpenseId||r.linkedSupplierTransactionId||'']),
'銀行照合一覧.csv':rows(['ID','日付','口座','摘要','入金','出金','金額','matched/unmatched','状態','対応区分','対応ID','payment','未処理項目'],inYear(data.bankTransactions||[],'bankTransactionDate'),['bankTxnId','bankTransactionDate','bankAccount','description','incoming','outgoing',r=>(r.incoming||0)-(r.outgoing||0),r=>r.status==='照合済'?'matched':r.status==='除外'?'excluded':'unmatched','status','matchType','matchId','paymentId',r=>!['照合済','除外'].includes(r.status)?r.description:'']),
'月次集計.csv':[['月','売上','銀行入金','現金入金','入金合計','月末未収','支出','現金支出','収支差額',...A.CATEGORIES],...a.months.map(m=>[m.month,m.sales,m.bankIncome,m.cashIncome,m.income,m.receivables,m.expenseTotal,m.cashExpenses,m.cashFlowDifference,...A.CATEGORIES.map(c=>m.categories[c])])],
'年間集計.csv':[['開始日','終了日','項目','金額'],...Object.entries(metrics).map(([k,v])=>[a.start,a.end,k,v])],
'帳票一覧.csv':rows(['ID','種類','請求日','売上日','入金日','金額','状態','売上ID','訂正元','訂正先','重複元','理由'],(data.documents||[]).filter(r=>['invoiceDate','salesDate','paymentDate'].some(k=>r[k]>=a.start&&r[k]<=a.end)),['documentId','docType','invoiceDate','salesDate','paymentDate','amount',r=>r.status||'active','saleId','revisedFromDocumentId','revisedToDocumentId','duplicateOfDocumentId','reason']),
'訂正・無効履歴.csv':rows(['誰','時間','entity','ID','action','before','after','reason'],audit(data,year).filter(r=>r.entityType==='documents'),['userId',timestamp,'entityType','entityId','action',r=>json(r.before),r=>json(r.after),r=>r.reason||r.after?.reason||'']),
'監査履歴.csv':rows(['誰','時間','entity','ID','action','before','after','reason'],audit(data,year,user,entity),['userId',timestamp,'entityType','entityId','action',r=>json(r.before),r=>json(r.after),r=>r.reason||r.after?.reason||r.after?.deleteReason||''])};
const supplier=[['仕入先ID','仕入先','月 / 年度','前払','月次材料請求','支払','調整・相殺','期首残高','期末残高']];for(const s of (data.suppliers||[]).filter(A.live)){for(const m of [...a.months.map(x=>x.month),'年度合計']){const ts=(data.supplierTransactions||[]).filter(t=>A.live(t)&&t.supplierId===(s.supplierId||s.id)&&t.date>=a.start&&t.date<=a.end&&(m==='年度合計'||t.date.slice(0,7)===m)),start=m==='年度合計'?a.start:m+'-01',end=m==='年度合計'?a.end:new Date(Date.UTC(+m.slice(0,4),+m.slice(5),0)).toISOString().slice(0,10),prior=new Date(Date.parse(start)-86400000).toISOString().slice(0,10);supplier.push([s.supplierId||s.id,s.supplierName,m,...['prepayment','monthlyInvoice','payment','adjustment'].map(type=>sum(ts.filter(t=>t.type===type))),A.supplierBalance(s,data.supplierTransactions||[],prior),A.supplierBalance(s,data.supplierTransactions||[],end)]);}}files['仕入先取引一覧.csv']=supplier;return Object.fromEntries(Object.entries(files).map(([n,r])=>[n,A.csv(r)]));}
const secret=k=>/password|passwd|token|secret|credential|private.?key|service.?account|authorization/i.test(k);
function sanitize(v){if(Array.isArray(v))return v.map(sanitize);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).filter(([k])=>!secret(k)).map(([k,x])=>[k,sanitize(x)]));return v;}
function backup(rows,who){assertAdmin(who);return {schemaVersion:4,companyId:'tsukinowa',exportedAt:new Date().toISOString(),records:sanitize(Object.fromEntries(COLLECTIONS.map(n=>[n,rows[n]||[]])))};}
function validateBackup(value,who){assertAdmin(who);const errors=[],counts={};if(value?.schemaVersion!==4)errors.push('schemaVersion は 4 が必要です。');if(value?.companyId!=='tsukinowa')errors.push('companyId が一致しません。');if(!value?.exportedAt||!Number.isFinite(Date.parse(value.exportedAt)))errors.push('exportedAt が不正です。');const records=value?.records;if(!records||typeof records!=='object'||Array.isArray(records))errors.push('records が不正です。');else{for(const n of COLLECTIONS){const rs=n==='receivables'&&records[n]===undefined?[]:records[n];if(!Array.isArray(rs)){errors.push(n+' が配列ではありません。');continue;}counts[n]=rs.length;const ids=new Set();for(const r of rs){if(!r||typeof r.id!=='string'||!r.id||ids.has(r.id)||(n!=='auditLogs'&&(!Number.isInteger(r.revision)||r.revision<1))||(n!=='auditLogs'&&(!r.payload||typeof r.payload!=='object')))errors.push(n+' レコード形式 / ID / revision が不正です。');ids.add(r?.id);}}for(const n of Object.keys(records))if(!COLLECTIONS.includes(n))errors.push('未知の collection: '+n);}
const walk=v=>{if(v&&typeof v==='object')for(const [k,x] of Object.entries(v)){if(secret(k))errors.push('秘密情報のキー: '+k);walk(x);}};walk(value);return {valid:!errors.length,errors,counts,total:Object.values(counts).reduce((n,x)=>n+x,0),schemaVersion:value?.schemaVersion,exportedAt:value?.exportedAt};}
return {COLLECTIONS,assertAdmin,flatten,period,effective,annual,audit,checks,exports,backup,validateBackup};
});
