// Real browser UI and real Firestore emulator. Only Authentication and PDF rendering are test adapters.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const {initializeTestEnvironment}=require('@firebase/rules-unit-testing');
const root=path.join(__dirname,'..');
const driver=`window.createTsukinowaFirebaseDriver=async()=>{
 const a=await import('/sdk/firebase-app.js'),f=await import('/sdk/firebase-firestore.js');let db,cb;
 return {initialize:async()=>{},observeAuth:next=>{cb=next;next(null);return()=>{}},claims:async u=>u.claims,
 signIn:async email=>{const role=email.startsWith('admin')?'admin':'staff';db=f.getFirestore(a.initializeApp({projectId:'demo-tsukinowa'},crypto.randomUUID()));f.connectFirestoreEmulator(db,'127.0.0.1',8080,{mockUserToken:{sub:'ui-'+role,role,companyId:'tsukinowa'}});await cb({uid:'ui-'+role,email,claims:{role,companyId:'tsukinowa'}})},signOut:async()=>cb(null),
 listen:(p,m,next,error)=>f.onSnapshot(m?f.collection(db,p):f.doc(db,p),{includeMetadataChanges:true},s=>next(m?s.docs.map(d=>({id:d.id,...d.data()})):s.exists()?{id:s.id,...s.data()}:null,{fromCache:s.metadata.fromCache}),error),
 list:async p=>(await f.getDocsFromServer(f.collection(db,p))).docs.map(d=>({id:d.id,...d.data()})),
 transaction:fn=>f.runTransaction(db,tx=>fn({get:async p=>{const s=await tx.get(f.doc(db,p));return s.exists()?s.data():null},set:(p,v)=>tx.set(f.doc(db,p),v),delete:p=>tx.delete(f.doc(db,p))})),timestamp:f.serverTimestamp,
 digest:async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),b=>b.toString(16).padStart(2,'0')).join('')};};`;
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;try{
 if(pathname==='/firebase-config.json'){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({enabled:true,companyId:'tsukinowa',firebase:{apiKey:'test',projectId:'demo-tsukinowa',authDomain:'test',appId:'test'}}));}
 if(pathname==='/js/firebase-driver.js'){res.setHeader('Content-Type','text/javascript');return res.end(driver);}
 if(pathname.startsWith('/sdk/')){res.setHeader('Content-Type','text/javascript');return res.end(fs.readFileSync(path.join(root,'node_modules/firebase',path.basename(pathname)),'utf8').replaceAll('https://www.gstatic.com/firebasejs/12.19.0/','/sdk/'));}
 const file=path.join(root,pathname==='/'?'index.html':pathname);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.html')?'text/html':'application/octet-stream');res.end(fs.readFileSync(file));
 }catch{res.statusCode=404;res.end();}});
(async()=>{
 const env=await initializeTestEnvironment({projectId:'demo-tsukinowa',firestore:{rules:fs.readFileSync('firestore.rules','utf8')}});await env.clearFirestore();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true}),errors=[];
 try{
 async function device(role,width){const ctx=await browser.newContext({viewport:{width,height:900},serviceWorkers:'block'}),p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.type()==='prompt'?d.accept('2026-10-01'):d.type()==='confirm'?d.accept():d.dismiss());await p.route('https://**/*',r=>r.fulfill({body:''}));await p.goto(base);await p.waitForFunction(()=>document.getElementById('cloudStatus').textContent==='未ログイン');await p.locator('#bizCloudAccountButton').click();await p.locator('#cloudEmail').fill(role+'@example.com');await p.locator('#cloudPassword').fill('password');await p.locator('#cloudLogin').click();await p.waitForFunction(()=>document.getElementById('coreSyncStatus').textContent==='クラウド同期済');await p.getByRole('button',{name:'閉じる',exact:true}).click();return p;}
 const phone=await device('staff',390),desktop=await device('admin',1280);
 await phone.evaluate(()=>{bizSwitchPage('chohyo');setDocType('estimate');document.getElementById('customerName').value='スマホ見積';document.getElementById('invoiceDate').value='2026-09-20';document.getElementById('salesDate').value='2026-10-01';items=[{content:'施工',qty:1,unit:'式',price:90909.09,taxable:true}];recalc();saveConfirmedHistory();});
 await desktop.waitForFunction(()=>bizState.estimates.length===1);assert.equal(await desktop.evaluate(()=>bizState.sales.length),0);
 const estimateId=await desktop.evaluate(()=>bizState.estimates[0].id);await desktop.evaluate(id=>bizAcceptEstimate(id,false),estimateId);await phone.waitForFunction(()=>bizState.estimates[0]?.status==='受注');
 await desktop.evaluate(id=>bizConvertEstimateRecordToInvoice(id),estimateId);await desktop.evaluate(()=>saveConfirmedHistory());await phone.waitForFunction(()=>bizState.sales.length===1);
 const invoiceId=await phone.evaluate(()=>bizState.sales[0].documentId);
 await desktop.evaluate(()=>{window.pdfSaves=0;window.html2pdf=()=>{const canvas=document.createElement('canvas');canvas.width=210;canvas.height=297;const pdf={internal:{getNumberOfPages:()=>1},deletePage(){},addPage(){},addImage(){},save(){window.pdfSaves++}};const worker={set(){return worker},from(){return worker},toCanvas(){return worker},toPdf(){return worker},get:key=>Promise.resolve(key==='canvas'?canvas:pdf)};return worker;};window.mockPdfRenderer=window.html2pdf;});
 for(let i=0;i<3;i++){await desktop.evaluate(id=>redownloadSavedDoc(loadConfirmedHistory().findIndex(s=>s.documentId===id)),invoiceId);await desktop.waitForFunction(n=>window.pdfSaves===n,i+1);await desktop.waitForFunction(()=>TsukinowaBusinessUI.getSync().getQueue().length===0);}
 assert.equal(await desktop.evaluate(()=>bizState.sales.length),1);
 // Standalone receipts use the same customer/amount as an invoice without guessing a link.
 const accountingSnapshot=p=>p.evaluate(async()=>{const c=TsukinowaBusinessUI.getClient(),out={};for(const name of ['sales','payments','receivables','bankTransactions','cashLedger','calendarLinks'])out[name]=await c.listRecords(name);return out;});
 for(const p of [phone,desktop]){
  const before=await accountingSnapshot(desktop);
  const standalone=await p.evaluate(async()=>{selectSaleForPayment(bizState.sales[0].id);setDocType('receipt');document.getElementById('customerName').value=bizState.sales[0].customer;document.getElementById('receiptTotal').value=bizState.sales[0].amount;document.getElementById('invoiceDate').value='2026-09-23';document.getElementById('paymentMethod').value='銀行振込';document.getElementById('tadashi').value='工事代として';document.getElementById('remarks').value='独立領収書';recalc();saveConfirmedHistory();await TsukinowaBusinessUI.getSync().flush();return collectFormState();});
  assert.equal(standalone.saleId,'');assert.equal(standalone.paymentDate,standalone.invoiceDate);assert.match(standalone.invoiceNo,/^\d{8}-\d{4}-\d{2,}$/);
  await desktop.waitForFunction(id=>loadConfirmedHistory().some(h=>h.documentId===id),standalone.documentId);
  const doc=await desktop.evaluate(async id=>(await TsukinowaBusinessUI.getClient().listRecords('documents')).find(r=>r.id===id).payload,standalone.documentId);assert.equal(doc.paymentId,'');assert.equal(doc.saleId,'');
  assert.equal(await p.locator('#receiptPaymentDate').count(),0);assert.match(await p.locator('label[for="receiptSale"]').innerText(),/任意/);
  for(let i=0;i<2;i++){const n=await desktop.evaluate(()=>pdfSaves);await desktop.evaluate(id=>redownloadSavedDoc(loadConfirmedHistory().findIndex(s=>s.documentId===id)),standalone.documentId);await desktop.waitForFunction(n=>pdfSaves===n,n+1);}
  if(process.env.HTML2PDF_BUNDLE){await p.addScriptTag({path:process.env.HTML2PDF_BUNDLE});const [download]=await Promise.all([p.waitForEvent('download'),p.evaluate(()=>doPrint())]);const target=path.join(root,'../standalone-'+(p===phone?'390':'1280')+'.pdf');await download.saveAs(target);const bytes=fs.readFileSync(target);assert.equal(bytes.subarray(0,5).toString(),'%PDF-');assert(bytes.length>10000);if(p===desktop)await desktop.evaluate(()=>window.html2pdf=window.mockPdfRenderer);}
  assert.deepEqual(await accountingSnapshot(desktop),before);
 }
 for(const amount of [50000,20000]){await phone.evaluate(amount=>{setDocType('receipt');document.getElementById('receiptSale').value=bizState.sales[0].id;document.getElementById('customerName').value=bizState.sales[0].customer;document.getElementById('paymentMethod').value='現金';document.getElementById('invoiceDate').value='2026-09-22';document.getElementById('receiptTotal').value=amount;recalc();saveConfirmedHistory();},amount);await phone.waitForFunction(()=>TsukinowaBusinessUI.getSync().getQueue().length===0);}
 await desktop.waitForFunction(()=>bizState.payments.length===2);assert.deepEqual(await desktop.evaluate(()=>[bizState.sales[0].amount,bizPaid(bizState.sales[0]),bizOutstanding(bizState.sales[0])]),[100000,70000,30000]);
 const linked=await desktop.evaluate(()=>loadConfirmedHistory().find(h=>h.docType==='receipt'&&h.saleId));
 const linkedBefore=await accountingSnapshot(desktop);
 for(let i=0;i<2;i++){const n=await desktop.evaluate(()=>pdfSaves);await desktop.evaluate(id=>redownloadSavedDoc(loadConfirmedHistory().findIndex(h=>h.documentId===id)),linked.documentId);await desktop.waitForFunction(n=>pdfSaves===n,n+1);}
 assert.deepEqual(await accountingSnapshot(desktop),linkedBefore);
 assert.equal(await desktop.evaluate(async id=>(await TsukinowaBusinessUI.getClient().listRecords('payments')).filter(r=>r.payload.documentId===id).length,linked.documentId),1);
 assert.equal(await desktop.evaluate(()=>bizState.payments.every(p=>p.paymentDate==='2026-09-22')),true);
 await phone.context().setOffline(true);await phone.evaluate(()=>{setDocType('receipt');document.getElementById('receiptSale').value=bizState.sales[0].id;document.getElementById('customerName').value=bizState.sales[0].customer;document.getElementById('paymentMethod').value='現金';document.getElementById('invoiceDate').value='2026-09-22';document.getElementById('receiptTotal').value=1000;saveConfirmedHistory();});assert.equal(await phone.evaluate(()=>TsukinowaBusinessUI.getSync().getQueue().length),1);await phone.context().setOffline(false);await desktop.waitForFunction(()=>bizState.payments.length===3);
 // Formal originals cannot be overwritten; admin creates a revision through the saved-doc UI.
 await desktop.evaluate(()=>bizSwitchPage('savedDocs'));
 await desktop.locator('#allSavedDocsList').getByRole('button',{name:'訂正版を作成',exact:true}).first().waitFor();
 await desktop.evaluate(id=>manageFormalDocument(loadConfirmedHistory().findIndex(x=>x.documentId===id),'revision'),invoiceId);
 await desktop.locator('#customerName').fill('管理者訂正');await desktop.evaluate(()=>{document.getElementById('customerCompany').value='法人テスト';document.getElementById('customerAddress').value='東京都';});
 await desktop.getByRole('button',{name:'正式保存',exact:true}).click();
 await phone.waitForFunction(id=>loadConfirmedHistory().some(d=>d.documentId===id&&d.documentStatus==='revised'),invoiceId);
 assert.equal(await desktop.evaluate(()=>bizState.sales.length),1);assert.equal(await desktop.evaluate(()=>bizState.sales[0].customer),'管理者訂正');
 assert.equal(await desktop.evaluate(()=>bizOutstanding(bizState.sales[0])),29000);
 await phone.evaluate(()=>bizSwitchPage('savedDocs'));assert.equal(await phone.getByRole('button',{name:'訂正版を作成',exact:true}).count(),0);assert((await phone.locator('#allSavedDocsList').innerText()).includes('訂正済'));
 await phone.evaluate(id=>{applyFormState(loadConfirmedHistory().find(s=>s.documentId===id));document.getElementById('customerName').value='古い編集';saveConfirmedHistory();},invoiceId);
 assert.equal(await phone.evaluate(()=>TsukinowaBusinessUI.getSync().getQueue().length),0);

 // Phase three: actual accounting controls and all six export paths.
 await desktop.evaluate(()=>{bizSwitchPage('expenses');document.getElementById('expDate').value='2026-10-02';document.getElementById('expCategory').value='交通費';document.getElementById('expMethod').value='現金';document.getElementById('expAmount').value='10000';document.getElementById('expVendor').value='交通テスト';return addExpense();});
 await desktop.waitForFunction(()=>TsukinowaAccountingUI.getData().expenses.length===1);assert.equal(await desktop.evaluate(()=>TsukinowaAccountingUI.getData().cashLedger.filter(x=>x.linkedExpenseId).length),1);
 await desktop.evaluate(()=>{bizSwitchPage('suppliers');document.getElementById('supplierName').value='材料商';document.getElementById('supplierOpeningDate').value='2026-10-01';document.getElementById('supplierOpening').value='0';return accountingSaveSupplier();});
 await desktop.waitForFunction(()=>TsukinowaAccountingUI.getData().suppliers.length===1);
 for(const [date,type,amount] of [['2026-10-05','prepayment',1000000],['2026-10-20','prepayment',1000000],['2026-10-31','monthlyInvoice',1438620]]){await desktop.evaluate(({date,type,amount})=>{document.getElementById('supplierSelect').value=TsukinowaAccountingUI.getData().suppliers[0].id;document.getElementById('supplierTxnDate').value=date;document.getElementById('supplierTxnType').value=type;document.getElementById('supplierAmount').value=amount;document.getElementById('supplierDescription').value='材料仕入';document.getElementById('supplierInvoiceMonth').value='2026-10';return accountingSaveSupplierTransaction();},{date,type,amount});await desktop.waitForFunction(()=>TsukinowaBusinessUI.getSync().getQueue().length===0);}
 await desktop.waitForFunction(()=>TsukinowaAccountingUI.getData().suppliers[0].currentBalance===561380);assert((await desktop.locator('#supplierRows').innerText()).includes('561,380'));
 await desktop.screenshot({path:path.join(root,'../accounting-suppliers.png')});
 await desktop.evaluate(()=>bizSwitchPage('bank'));await desktop.locator('#bankFile').setInputFiles({name:'bank.csv',mimeType:'text/csv',buffer:Buffer.from('日付,摘要,入金,出金,取引ID\n2026/10/06,管理者訂正,5000,,ui-bank-1\n')});
 for(let i=0;i<2;i++){await desktop.evaluate(()=>importBankCsv());await desktop.waitForFunction(()=>TsukinowaBusinessUI.getSync().getQueue().length===0);}
 assert.equal(await desktop.evaluate(()=>TsukinowaAccountingUI.getData().bankTransactions.length),1);
 await desktop.evaluate(()=>{const b=TsukinowaAccountingUI.getData().bankTransactions[0];accountingConfirmBank(b.id,{targetType:'sale',targetId:bizState.sales[0].id,paymentId:''});});
 await desktop.waitForFunction(()=>TsukinowaAccountingUI.getData().bankTransactions[0].status==='照合済');assert.equal(await desktop.evaluate(()=>bizOutstanding(bizState.sales[0])),24000);
 await desktop.evaluate(()=>{document.getElementById('monthlyMonth').value='2026-10';bizSwitchPage('monthly');});assert.equal(await desktop.locator('#mPayments').textContent(),'¥5,000');assert.equal(await desktop.locator('#mExpenses').textContent(),'¥1,448,620');
 for(const kind of ['monthly','expenses','sales','receivables','suppliers','bank']){const pending=desktop.waitForEvent('download');await desktop.evaluate(k=>accountingExport(k),kind);const download=await pending,bytes=fs.readFileSync(await download.path());assert.equal(bytes.subarray(0,3).toString('hex'),'efbbbf');}
 const backupDownload=desktop.waitForEvent('download');await desktop.evaluate(()=>exportBackup());const accountingBackup=JSON.parse(fs.readFileSync(await (await backupDownload).path(),'utf8'));assert(accountingBackup.records.suppliers.length===1);assert(accountingBackup.records.cashLedger.length>0);
 await phone.evaluate(()=>bizSwitchPage('bank'));assert(!(await phone.locator('#pageBank').isVisible()));await phone.evaluate(()=>bizSwitchPage('suppliers'));assert(!(await phone.locator('#pageSuppliers').isVisible()));
 await desktop.screenshot({path:path.join(root,'../accounting-monthly.png')});
 console.log('PASS accounting UI: expense + cash, supplier 561380 balance, duplicate CSV, bank match, monthly date totals, staff navigation guards and 6 UTF-8 BOM exports');

 // Unified pre-production acceptance: actual UI + actual Firestore, both widths.
 for(const width of [390,1280]){
  await desktop.setViewportSize({width,height:900});
  const cashId=await desktop.evaluate(async width=>{bizSwitchPage('chohyo');setDocType('receipt');document.getElementById('customerName').value='下村 健朗 '+width;document.getElementById('invoiceDate').value='2026-10-05';document.getElementById('receiptTotal').value=110000;document.getElementById('tadashi').value='クロス張替';document.getElementById('paymentMethod').value='現金';recalc();saveConfirmedHistory();await TsukinowaBusinessUI.getSync().flush();return collectFormState().documentId;},width);
  await desktop.waitForFunction(id=>bizState.sales.some(s=>s.documentId===id),cashId);
  const cash=await desktop.evaluate(id=>{const s=bizState.sales.find(s=>s.documentId===id);return [s.sourceType,s.amount,s.invoiceDate,bizPaid(s),bizOutstanding(s),bizState.payments.filter(p=>p.saleId===s.id).length,TsukinowaAccountingUI.getData().cashLedger.filter(r=>r.linkedPaymentId===('pay_'+id)).length];},cashId);assert.deepEqual(cash,['receipt-cash',110000,'',110000,0,1,1]);
  await desktop.evaluate(()=>{document.getElementById('salesMonth').value='2026-10';bizSwitchPage('sales');});assert.match(await desktop.locator('#salesRows').innerText(),/110,000/);
  const unpaid=await desktop.evaluate(async width=>{bizSwitchPage('chohyo');setDocType('invoice');document.getElementById('customerName').value='琢居株式会社 void '+width;document.getElementById('invoiceDate').value='2026-10-03';document.getElementById('salesDate').value='2026-10-03';items=[{content:'クロス張替',qty:1,price:97160,taxable:true}];recalc();saveConfirmedHistory();await TsukinowaBusinessUI.getSync().flush();return collectFormState().documentId;},width);
  await desktop.waitForFunction(id=>loadConfirmedHistory().some(d=>d.documentId===id),unpaid);await desktop.evaluate(()=>bizSwitchPage('savedDocs'));
  const card=desktop.locator('#allSavedDocsList .biz-card').filter({hasText:'ID: '+unpaid});await card.getByRole('button',{name:'無効にする',exact:true}).click();await desktop.waitForFunction(id=>loadConfirmedHistory().some(d=>d.documentId===id&&d.documentStatus==='void'),unpaid);assert.match(await card.innerText(),/無効/);assert.equal(await card.getByRole('button',{name:'入金登録',exact:true}).count(),0);
  assert.equal(await desktop.evaluate(id=>bizState.sales.some(s=>s.documentId===id),unpaid),false);await desktop.evaluate(()=>bizSwitchPage('sales'));assert(!(await desktop.locator('#paymentSale').innerText()).includes('void '+width));
  const estimates=[];for(let i=0;i<2;i++)estimates.push(await desktop.evaluate(async ({width,i})=>{bizSwitchPage('chohyo');setDocType('estimate');document.getElementById('customerName').value='李月華 '+width;document.getElementById('invoiceDate').value='2026-10-06';document.getElementById('salesDate').value='';items=[{content:'クロス張替',qty:1,price:50000},{content:'穴補修',qty:1,price:10000},{content:'部分的補修',qty:1,price:500},{content:'出張費',qty:1,price:100}];recalc();saveConfirmedHistory();await TsukinowaBusinessUI.getSync().flush();return collectFormState().documentId;},{width,i}));
  await desktop.waitForFunction(id=>loadConfirmedHistory().some(h=>h.documentId===id),estimates[1]);await desktop.evaluate(()=>bizSwitchPage('estimates'));assert.match(await desktop.locator('#estimateRows').innerText(),/クロス張替・穴補修/);assert(!(await desktop.locator('#estimateRows').innerText()).includes('クロス張替・穴補修・その他'));
  await desktop.evaluate(()=>bizSwitchPage('savedDocs'));await desktop.locator('#allSavedDocsList .biz-card').filter({hasText:'ID: '+estimates[1]}).getByRole('button',{name:'重複として無効',exact:true}).click();const dialog=desktop.locator('dialog[open]');assert(await dialog.isVisible());assert.match(await dialog.locator('select').innerText(),/No\..*2026-10-06.*66,660/);await dialog.getByRole('button',{name:'重複として無効',exact:true}).click();await desktop.waitForFunction(id=>loadConfirmedHistory().some(d=>d.documentId===id&&d.documentStatus==='duplicate'),estimates[1]);
  const orphan='orphan-'+width;await desktop.evaluate(async id=>{await TsukinowaBusinessUI.getSync().service.execute({type:'migrateRecord',collection:'documents',id,payload:{documentId:id,docType:'estimate',sourceType:'system-error',confirmed:false,snapshot:{documentId:id,docType:'estimate',customerName:'誤生成',invoiceDate:'2026-10-06',items:[]}},operationId:crypto.randomUUID()});},orphan);await desktop.waitForFunction(id=>loadConfirmedHistory().some(h=>h.documentId===id),orphan);await desktop.evaluate(()=>bizSwitchPage('savedDocs'));const backup=desktop.waitForEvent('download');await desktop.locator('#allSavedDocsList .biz-card').filter({hasText:'ID: '+orphan}).getByRole('button',{name:'誤登録を削除'}).click();await backup;await desktop.waitForFunction(id=>!loadConfirmedHistory().some(h=>h.documentId===id),orphan);
  assert(await desktop.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await desktop.screenshot({path:path.join(root,'../production-gate-'+width+'.png')});console.log('PASS unified UI '+width+'px: screenshot cash110000, unpaid106876 void, live statistics/candidates removed, duplicate dropdown, classification, orphan backup/audit/delete');
 }
 assert.deepEqual(errors,[]);await phone.screenshot({path:path.join(root,'../business-mobile.png')});await desktop.screenshot({path:path.join(root,'../business-desktop.png')});console.log('PASS actual 390px/1280px UI: realtime estimate/acceptance, invoice, independent bank receipts, cash receipt gate, explicit payment + repeat PDF deduplication, 2 partial receipts, offline queue recovery, conflict preservation');
 }finally{await browser.close();server.close();await env.cleanup();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
