const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const C=require('../js/cloud-core'),B=require('../js/business-domain'),H=require('../js/historical-import'),O=require('../js/outstanding'),A=require('../js/accounting'),Y=require('../js/year-end');
const draft={customerName:'dynast合同会社',invoiceNo:'20260801-001',issueDate:'2026-08-01',dueDate:'2026-09-01',invoiceAmount:779379,billingMonth:'2026-07',remarks:'2026年7月分',items:[]};
async function harness(role='admin'){
 const rows=new Map();let cb;
 const digest=async s=>crypto.createHash('sha256').update(s).digest('hex'),driver={initialize:async()=>{},observeAuth:f=>(cb=f,()=>{}),claims:async u=>u.claims,digest,timestamp:()=>123,
 list:async p=>[...rows].filter(([k])=>k.startsWith(p+'/')).map(([k,v])=>({id:k.split('/').at(-1),...v})),transaction:async f=>{const writes=[];const result=await f({get:async p=>rows.get(p)||null,set:(p,v)=>writes.push([p,v])});for(const [p,v]of writes)rows.set(p,v);return result;}};
 const client=C.createClient(driver);await client.start({enabled:true,companyId:'tsukinowa',firebase:{apiKey:'x',authDomain:'x',projectId:'demo',appId:'x'}});await cb({uid:role,claims:{role,companyId:'tsukinowa'}});
 const service=B.createService(client),list=n=>[...rows].filter(([p])=>p.includes('/'+n+'/')).map(([p,r])=>({id:p.split('/').at(-1),...r}));
 const command=(options={})=>({type:'historicalPdfImport',operationId:crypto.randomUUID(),documentId:'doc_'+crypto.randomUUID(),draft,sourceHash:'a'.repeat(64),sourceFileName:'old.pdf',createSale:false,linkedSaleId:'',...options});
 return {rows,service,list,command};
}
test('text parsing preserves original invoice fields; uncertain/scan input stays editable',()=>{assert.deepEqual(H.parseText('dynast合同会社 御中\n請求書No.：20260801-001\n発行日：2026年8月1日\n支払期限：2026/09/01\nご請求金額：779,379円\n2026年7月分'),draft);assert.equal(H.parseText('').invoiceNo,'');assert.throws(()=>H.validate({...draft,issueDate:'2026-02-31'}));});
test('default imports no sale, preserves dates and amount; same PDF/no/tuple are blocked, even edited fields',async()=>{const h=await harness(),cmd=h.command(),r=await h.service.execute(cmd);assert.equal(h.list('sales').length,0);assert.equal(h.list('receivables').length,1);const d=h.list('documents')[0].payload;assert.equal(d.status,'active');assert.equal(d.snapshot.invoiceNo,draft.invoiceNo);assert.equal(d.issueDate,draft.issueDate);assert.equal(d.dueDate,draft.dueDate);assert.equal(d.amount,779379);assert.equal(d.snapshot.items.length,0);assert.equal(d.whetherCreatedSale,false);assert.equal(h.list('auditLogs')[0].action,'historicalPdfImport');assert.equal(h.list('auditLogs')[0].sourceHash,cmd.sourceHash);assert.deepEqual(await h.service.execute(cmd),r);for(const options of [{},{sourceHash:'b'.repeat(64)},{draft:{...draft,invoiceNo:'changed',invoiceAmount:1}},{sourceHash:'c'.repeat(64),draft:{...draft,invoiceNo:'other'}}])await assert.rejects(h.service.execute(h.command(options)),/重複/);assert.equal(h.list('documents').length,1);});
test('existing corresponding sale is linked, preserves value/tax/payments and never creates sale',async()=>{const h=await harness(),p={id:'legacy',customer:draft.customerName,invoiceDate:draft.issueDate,salesDate:'2026-07-31',amount:779379,taxAmount:70853,paymentIds:[],paymentVersion:0};h.rows.set('companies/tsukinowa/sales/legacy',{payload:p,revision:1});const r=await h.service.execute(h.command({linkedSaleId:'legacy',createSale:true}));assert.equal(r.saleId,'legacy');assert.equal(r.whetherCreatedSale,false);assert.equal(h.list('sales').length,1);assert.equal(h.list('sales')[0].payload.taxAmount,70853);assert.equal(h.list('sales')[0].payload.salesDate,'2026-07-31');});
test('explicit B creates exactly one historical sale; repeat operations/uploads never create two',async()=>{const h=await harness(),cmd=h.command({createSale:true});await h.service.execute(cmd);await h.service.execute(cmd);await assert.rejects(h.service.execute(h.command({createSale:true})),/重複/);assert.equal(h.list('sales').length,1);assert.equal(h.list('receivables').length,0);assert.equal(h.list('sales')[0].payload.amount,779379);assert.equal(h.list('auditLogs')[0].whetherCreatedSale,true);});
test('A supports partial payment, balance notice, bank confirmation and annual receivables without sales/tax',async()=>{const h=await harness(),r=await h.service.execute(h.command());await h.service.execute({type:'payment',operationId:'pay',paymentId:'pay1',saleId:r.receivableId,documentId:r.documentId,amount:770379,paymentDate:'2026-08-25',method:'銀行振込'});let v=O.view(h.list('documents')[0],h.list('receivables')[0].payload,h.list('payments'));assert.deepEqual([v.invoiceAmount,v.paidAmount,v.outstandingAmount,v.paymentStatus],[779379,770379,9000,'一部入金']);const before=JSON.stringify([...h.rows]);for(let i=0;i<2;i++)assert.equal(O.notice(v,'2026-10-02').outstandingAmount,9000);assert.equal(JSON.stringify([...h.rows]),before);await h.service.execute({type:'confirmBank',operationId:'confirm',bankId:'oldbank',saleId:r.receivableId,pendingPaymentId:'pay1',amount:770379,paymentDate:'2026-08-25'});v=O.view(h.list('documents')[0],h.list('receivables')[0].payload,h.list('payments'));assert.equal(v.paidAmount,770379);assert.equal(h.list('sales').length,0);const data=Y.flatten(Object.fromEntries(Y.COLLECTIONS.map(n=>[n,h.list(n)])));const annual=Y.annual(data,2025);assert.equal(annual.sales,0);assert.equal(annual.bankIncome,770379);assert.equal(annual.receivables,9000);assert(!Y.exports(data,2025,{role:'admin',companyId:'tsukinowa'})['年間売上一覧.csv'].includes('dynast'));assert.equal(A.monthly({...data,sales:data.receivables},'2026-08').sales,0);});
test('staff historical import cannot reach any write',async()=>{const h=await harness('staff');await assert.rejects(h.service.execute(h.command()),/管理者/);assert.equal(h.rows.size,0);});
test('old backup without receivables validates; historical receivable survives new backups',()=>{const who={role:'admin',companyId:'tsukinowa'},backup=Y.backup({},who);delete backup.records.receivables;assert.equal(Y.validateBackup(backup,who).valid,true);});
test('undeployed optional receivables rules cannot stop legacy realtime synchronization',()=>{const S=require('../js/business-sync'),listeners={},statuses=[],who={role:'staff',user:{uid:'u'},projectId:'p',companyId:'tsukinowa'},store=new Map(),client={getState:()=>who,listen:(n,id,next,error)=>(listeners[n]={next,error},()=>{}),digest:async s=>s};const sync=S.createSync({client,storage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},onStatus:s=>statuses.push(s)});sync.start();for(const [n,l]of Object.entries(listeners))n==='receivables'?l.error({code:'permission-denied',message:'undeployed'}):l.next([],{fromCache:false});assert.equal(statuses.at(-1).state,'synced');assert.equal(statuses.at(-1).ready,true);sync.stop();});

test('inactive existing sale is surfaced and blocks an explicit second historical sale',async()=>{const h=await harness();h.rows.set('companies/tsukinowa/sales/inactive',{payload:{id:'inactive',customer:draft.customerName,invoiceDate:draft.issueDate,amount:draft.invoiceAmount,documentStatus:'void'},revision:1});assert.equal(H.check(draft,[],h.list('sales')).matches.length,1);await assert.rejects(h.service.execute(h.command({createSale:true,linkedSaleId:'inactive'})),/変更/);assert.equal(h.list('sales').length,1);assert.equal(h.list('documents').length,0);});
