const {test}=require('node:test'),assert=require('node:assert/strict'),Y=require('../js/year-end.js'),A=require('../js/accounting.js');
const admin={role:'admin',companyId:'tsukinowa'},staff={role:'staff',companyId:'tsukinowa'};
function fixture(){return {sales:[{id:'sale',documentId:'new',salesDate:'2025-10-01',invoiceDate:'2025-10-01',amount:1000},{id:'void',documentId:'void',salesDate:'2025-10-01',amount:1000},{id:'dup',documentStatus:'duplicate',salesDate:'2025-10-01',amount:1000},{id:'old',documentStatus:'revised',salesDate:'2025-10-01',amount:1000}],documents:[{id:'new',documentId:'new',status:'active',docType:'invoice',saleId:'sale'},{id:'old',documentId:'old',status:'revised',docType:'invoice',saleId:'sale'},{id:'void',status:'void'}],payments:[{id:'pay',saleId:'sale',amount:300,paymentDate:'2026-01-01',confirmation:'cash-received'},{id:'future',saleId:'sale',amount:700,paymentDate:'2026-10-01',confirmation:'bank-confirmed'}],expenses:[{id:'e',amount:120,expenseDate:'2026-09-30',category:'材料費',paymentMethod:'銀行振込'}],cashLedger:[{cashTxnId:'open',date:'2025-09-30',amount:100,type:'income'},{cashTxnId:'p',date:'2026-01-01',amount:300,type:'income',linkedPaymentId:'pay'},{cashTxnId:'e',date:'2026-02-01',amount:50,type:'expense'}],bankTransactions:[{id:'b',bankTxnId:'b',bankTransactionDate:'2026-09-01',status:'未照合',incoming:300,description:'待機'}]};}
test('annual equals 12 monthly sums, excludes void duplicate revised, partial cutoff receivable',()=>{const d=fixture(),a=Y.annual(d,2025);assert.equal(a.sales,1000);assert.equal(a.receivables,700);for(const key of ['sales','income','expenseTotal','cashFlowDifference'])assert.equal(a[key],a.months.reduce((n,m)=>n+m[key],0));assert.equal(a.categories.材料費,120);});
test('revision shared sale counted once and duplicate record reported',()=>{const d=fixture();d.sales.push({...d.sales[0]});d.documents.push({...d.documents[0],id:'extra',documentId:'extra'});assert.equal(Y.annual(d,2025).sales,1000);assert(Y.checks(d,2025).some(c=>c.type==='同一売上に複数有効請求書'));});
test('CSV package BOM, cash carries opening balance, bank unmatched, audit filtering',()=>{const d=fixture();d.auditLogs=[{id:'a',timestamp:{seconds:Date.parse('2026-01-01')/1000},userId:'u',entityType:'documents',action:'status change',before:{status:'active'},after:{status:'void',reason:'理由'}}];const files=Y.exports(d,2025,admin);assert.equal(Object.keys(files).length,12);for(const v of Object.values(files))assert(v.startsWith('\ufeff'));const cash=A.parseCSV(files['現金出納帳.csv'].slice(1));assert.equal(cash[1][5],'400');assert.equal(cash[2][5],'350');assert(files['銀行照合一覧.csv'].includes('unmatched'));assert(Y.checks(d,2025).some(c=>c.type==='未照合銀行入出金'));assert.equal(Y.audit(d,2025,'u','documents').length,1);assert.equal(Y.audit(d,2025,'other').length,0);});
test('staff denied exports backup preview audit access through admin boundary',()=>{for(const who of [staff,null,{role:'admin',companyId:'other'}]){assert.throws(()=>Y.exports(fixture(),2025,who));assert.throws(()=>Y.backup({},who));assert.throws(()=>Y.validateBackup({},who));assert.throws(()=>Y.assertAdmin(who));}});
test('backup contains collections metadata excludes nested secrets and validates without mutations',()=>{const rows=Object.fromEntries(Y.COLLECTIONS.map(n=>[n,[]]));rows.sales=[{id:'s',revision:1,payload:{amount:1,password:'bad',nested:{accessToken:'bad',serviceAccountSecret:'bad',private_key:'bad',description:'safe'}}}];const b=Y.backup(rows,admin),text=JSON.stringify(b);assert(!text.includes('bad'));assert.equal(b.companyId,'tsukinowa');assert.equal(b.schemaVersion,4);assert.equal(Y.validateBackup(b,admin).valid,true);assert.equal(Y.validateBackup(b,admin).total,1);b.records.sales.push(b.records.sales[0]);assert.equal(Y.validateBackup(b,admin).valid,false);b.schemaVersion=3;assert.equal(Y.validateBackup(b,admin).valid,false);});
test('checks missing paymentDate category abnormal cash and duplicate documentId',()=>{const d=fixture();d.payments.push({id:'missing',confirmation:'bank-confirmed',amount:1});d.expenses.push({id:'zero',amount:0,expenseDate:'2026-01-01'});d.cashLedger.push({cashTxnId:'negative',date:'2026-08-01',type:'expense',amount:10000});d.documents.push({...d.documents[0]});const types=Y.checks(d,2025).map(c=>c.type);for(const t of ['入金日未設定','分類未設定','金額0・異常金額','現金残高異常','同一 documentId 重複','無効・重複帳票の関連記録'])assert(types.includes(t),t);});

test('audit fiscal boundary uses Japan time',()=>{const d={auditLogs:[{timestamp:'2025-09-30T15:00:00Z',userId:'u'},{timestamp:'2026-09-30T15:00:00Z',userId:'u'}]};assert.equal(Y.audit(d,2025).length,1);});

test('invalid invoice anchors exclude both sales and income even for legacy inconsistent sale status',()=>{
 const A=require('../js/accounting');const data={documents:[{id:'invalid',status:'void'}],sales:[{id:'sale',documentId:'invalid',documentStatus:'active',amount:1000,salesDate:'2026-10-05',invoiceDate:'2026-10-05'}],payments:[{id:'pay',saleId:'sale',amount:1000,paymentDate:'2026-10-05',confirmation:'cash-received'}]};const m=A.monthly(data,'2026-10');assert.equal(m.sales,0);assert.equal(m.income,0);const y=require('../js/year-end').annual(data,2026);assert.equal(y.sales,0);assert.equal(y.income,0);
});
